// This project lints, decided on T-004. Every other project in this group does,
// and this one is a live site: `type-check` and the e2e suite catch types and
// behaviour and say nothing about unused code, missing hook dependencies, or the
// Next-specific mistakes that only cost anything in production.
//
// The rule set is named rather than assembled here. `eslint-config-next` knows
// about this framework's router, images and fonts, and somebody maintains it;
// a set argued into existence in this file would be worth less and rot faster.
// `core-web-vitals` is the half that catches what costs real users something.
//
// Imported directly, not through `@eslint/eslintrc`'s FlatCompat. Every guide
// still shows FlatCompat because it was needed when flat config was new, and on
// eslint 10 it dies inside its own error formatter ("Converting circular
// structure to JSON") before it can tell you what it disliked. This package has
// shipped a flat config since 15; there is nothing to convert.
import next from "eslint-config-next/core-web-vitals";
import tseslint from "typescript-eslint";

export default [
  {
    ignores: [
      ".next/**", "out/**", "build/**", "node_modules/**",
      "next-env.d.ts",
      // Generated by shadcn and updated by regenerating rather than editing.
      // Linting it produces findings nobody can act on without hand-editing a
      // file the next `shadcn add` overwrites.
      "src/components/ui/**",
      // Playwright's own output: a report, not source.
      "playwright-report/**", "test-results/**",
      // Agent worktrees. Each is a whole second checkout with its own `.next`
      // build output, so without this a lint run reads compiled turbopack
      // chunks and reports on machine-generated code nobody wrote.
      ".claude/worktrees/**", ".worktrees/**",
    ],
  },
  ...next,
  ...tseslint.configs.recommended,
  {
    rules: {
      // An unused argument prefixed with _ is a signature being honoured rather
      // than a mistake: a callback that must take three parameters and wants
      // the third.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],

      // The two React 19 rules below are warnings rather than errors, and that
      // is a deliberate hold, not a dismissal. They are counted in the ceiling,
      // so they cannot grow, and T-008 is where they get read one at a time.
      //
      // `refs` fires three times and every one of them points at
      // `handleSubmit(onSubmit)` in JSX, which is react-hook-form's. That looks
      // like the rule and that library disagreeing rather than this code being
      // wrong, but looking like it is not knowing it, and the way to find out
      // is to read all three rather than to assume from the shape.
      //
      // `set-state-in-effect` fires three times on deriving state from props
      // and on a debounced autocomplete. Those are real smells. They are also
      // working code on a live site, and the e2e suite does not cover the
      // autocomplete, so rewriting them to make a first lint run green is how
      // a lint ticket breaks production.
      "react-hooks/refs": "warn",
      "react-hooks/set-state-in-effect": "warn",
    },
  },
];
